// src/components/DarkModeToggle.tsx
"use client";

import { useState } from "react";

interface Props {
  className?: string;
}

function getInitialTheme(): "light" | "dark" {
  if (typeof document === "undefined") return "light";
  const current = document.documentElement.getAttribute("data-theme");
  return current === "dark" ? "dark" : "light";
}

export default function DarkModeToggle({ className }: Props) {
  const [theme, setTheme] = useState<"light" | "dark">(getInitialTheme);

  const toggle = () => {
    const next = theme === "light" ? "dark" : "light";
    setTheme(next);
    document.documentElement.setAttribute("data-theme", next);
    localStorage.setItem("theme", next);
  };

  return (
    <button
      className={className}
      onClick={toggle}
      aria-label={theme === "light" ? "다크 모드로 전환" : "라이트 모드로 전환"}
      title={theme === "light" ? "다크 모드" : "라이트 모드"}
    >
      {theme === "light" ? "\u{1F319}" : "\u{2600}\u{FE0F}"}
    </button>
  );
}

// src/lib/components/ui/DarkModeToggle.svelte
<script lang="ts">
	import { theme } from '$lib/stores/theme';
	import { Moon, Sun } from 'lucide-svelte';
</script>

<button
	onclick={theme.toggle}
	class="p-2 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors"
	aria-label={$theme === 'light' ? '다크 모드로 전환' : '라이트 모드로 전환'}
>
	{#if $theme === 'light'}
		<Moon size={20} strokeWidth={1.5} />
	{:else}
		<Sun size={20} strokeWidth={1.5} />
	{/if}
</button>
