// src/components/ui/DarkModeToggle.tsx
import { useEffect } from "react";
import { useThemeStore } from "@/store/useThemeStore";
import { Moon, Sun } from "lucide-react"

export function DarkModeToggle() {
  // Zustand store에서 현재 테마와 토글 함수를 꺼내옴
  const theme = useThemeStore((s) => s.theme)
  const toggleTheme = useThemeStore((s) => s.toggleTheme)

  // theme이 바뀔 때마다 실행됨
  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark')
  }, [theme])  // ← [theme]: theme이 바뀔 때만 실행하라는 의미

  return (
    <button
      onClick={toggleTheme}
      className="p-2 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors"
      aria-label={`${theme === 'light' ? '다크' : '라이트'} 모드로 전환`}
    >
      {theme === 'light'
        ? <Moon size={20} strokeWidth={1.5} />
        : <Sun size={20} strokeWidth={1.5} />
      }
    </button>
  )
}

// src/lib/components/ui/DarkModeToggle.svelte
<script lang="ts">
	import { theme } from '$lib/stores/theme';
	import { Moon, Sun } from 'lucide-svelte';
</script>

<button
	onclick={theme.toggle}
	class="p-2 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors"
	aria-label={$theme === 'light' ? '다크 모드로 전환' : '라이트 모드로 전환'}
>
	{#if $theme === 'light'}
		<Moon size={20} strokeWidth={1.5} />
	{:else}
		<Sun size={20} strokeWidth={1.5} />
	{/if}
</button>
