// src/components/blog/RightPanel.tsx
import { getBlogGraphData } from '@/lib/content/graph'
import { RelationGraph } from './RelationGraph'

export async function RightPanel({ children }: { children?: React.ReactNode }) {
  const graphData = await getBlogGraphData()

  return (
    <aside className="hidden xl:block">
      <div className="sticky top-24 space-y-6">
        <RelationGraph data={graphData} />
        {children}
      </div>
    </aside>
  )
}

// src/lib/components/blog/RightPanel.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import RelationGraph from './RelationGraph.svelte';
	import type { GraphData } from '$lib/content/graph';

	interface Props {
		graphData: GraphData;
		extra?: Snippet;
	}

	let { graphData, extra }: Props = $props();
</script>

<aside class="hidden xl:block">
	<div class="sticky top-24 space-y-6">
		<RelationGraph data={graphData} />
		{#if extra}
			{@render extra()}
		{/if}
	</div>
</aside>
