// src/lib/components/blog/TableOfContents.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { Heading } from '$lib/types/content';

	interface Props {
		headings: Heading[];
	}

	let { headings }: Props = $props();
	let activeId = $state('');

	let minLevel = $derived(
		headings.length > 0 ? Math.min(...headings.map((h) => h.level)) : 2
	);

	onMount(() => {
		const headingElements = headings
			.map((h) => document.getElementById(h.slug))
			.filter(Boolean) as HTMLElement[];

		if (headingElements.length === 0) return;

		const observer = new IntersectionObserver(
			(entries) => {
				const visible = entries
					.filter((e) => e.isIntersecting)
					.sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);

				if (visible.length > 0) {
					activeId = visible[0].target.id;
				}
			},
			{ rootMargin: '-80px 0px -60% 0px' }
		);

		headingElements.forEach((el) => observer.observe(el));

		return () => observer.disconnect();
	});
</script>

{#if headings.length > 0}
	<nav aria-label="목차">
		<p
			class="text-xs font-medium uppercase tracking-widest mb-3"
			style:color="var(--color-secondary)"
		>
			On this page
		</p>
		<ul class="space-y-1.5">
			{#each headings as h}
				{@const isActive = h.slug === activeId}
				{@const indent = (h.level - minLevel) * 0.75}
				<li>
					<a
						href="#{h.slug}"
						class="block text-xs leading-snug transition-colors hover:opacity-70"
						style:padding-left="{indent}rem"
						style:color={isActive ? 'var(--color-primary)' : 'var(--color-secondary)'}
						style:font-weight={isActive ? 500 : 400}
					>
						{h.text}
					</a>
				</li>
			{/each}
		</ul>
	</nav>
{/if}

// src/components/TableOfContents.tsx
import type { Heading } from "@/lib/types";

interface Props {
  headings: Heading[];
}

export default function TableOfContents({ headings }: Props) {
  const filteredHeadings = headings.filter((h) => h.depth >= 2 && h.depth <= 4);

  if (filteredHeadings.length === 0) return null;

  return (
    <>
      <nav className="toc-sidebar" aria-label="목차">
        <h4 className="toc-title">목차</h4>
        <ul className="toc-list">
          {filteredHeadings.map((heading) => (
            <li key={heading.slug} className={`toc-item depth-${heading.depth}`}>
              <a href={`#${heading.slug}`}>{heading.text}</a>
            </li>
          ))}
        </ul>
      </nav>

      <style>{`
        .toc-sidebar {
          position: sticky;
          top: 80px;
          max-height: calc(100vh - 100px);
          overflow-y: auto;
          padding-right: var(--spacing-md);
        }
        .toc-title {
          font-size: 0.8rem;
          text-transform: uppercase;
          letter-spacing: 0.08em;
          color: var(--gray);
          margin-bottom: var(--spacing-sm);
          font-family: var(--font-header);
        }
        .toc-list {
          list-style: none;
          padding: 0;
        }
        .toc-item {
          margin-bottom: 4px;
        }
        .toc-item a {
          display: block;
          font-size: 0.8rem;
          color: var(--gray);
          padding: 2px 0;
          line-height: 1.4;
          text-decoration: none;
          border-left: 2px solid transparent;
          padding-left: var(--spacing-sm);
          transition: color var(--transition), border-color var(--transition);
        }
        .toc-item a:hover {
          color: var(--text);
          border-left-color: var(--tertiary);
          opacity: 1;
        }
        .toc-item.depth-3 {
          padding-left: var(--spacing-md);
        }
        .toc-item.depth-4 {
          padding-left: var(--spacing-xl);
        }
      `}</style>
    </>
  );
}
