// src/app/blog/[slug]/page.tsx
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'

import { BlogArticle } from '@/components/blog/BlogArticle'
import { RightPanel } from '@/components/blog/RightPanel'
import { TableOfContents } from '@/components/blog/TableOfContents'

import { normalizeBlogReference } from '@/lib/content/blog-slug'
import { renderMarkdown } from '@/lib/content/mdx'
import {
  getAllBlogPosts,
  getBlogPostBySlug,
  getBlogReferenceLookup,
} from '@/lib/content/posts'

export const dynamicParams = false

export async function generateStaticParams() {
  const posts = await getAllBlogPosts()

  return posts.map((post) => ({
    slug: post.slug,
  }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const post = await getBlogPostBySlug(slug)

  if (!post) {
    return { title: 'Not Found' }
  }

  return {
    title: post.title,
    description: post.description,
    openGraph: {
      title: post.title,
      description: post.description,
      type: 'article',
      publishedTime: post.date.toISOString(),
    },
  }
}

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params

  const [post, references] = await Promise.all([
    getBlogPostBySlug(slug),
    getBlogReferenceLookup(),
  ])

  if (!post) notFound()

  const html = await renderMarkdown(post.content, {
    resolveWikiLink: (reference) => {
      const resolved = references.get(normalizeBlogReference(reference))

      if (!resolved) {
        return null
      }

      return {
        href: `/blog/${resolved.slug}`,
        title: resolved.title,
        description: resolved.description,
      }
    },
    resolveEmbed: (reference) => {
      const resolved = references.get(normalizeBlogReference(reference))

      if (!resolved) {
        return null
      }

      return {
        type: 'note',
        href: `/blog/${resolved.slug}`,
        title: resolved.title,
        description: resolved.description,
      }
    },
  })

  return (
    <>
      {/* 본문 */}
      <div className="flex justify-center">
        <BlogArticle
          title={post.title}
          date={post.date}
          readingTime={post.readingTime}
          tags={post.tags}
          cssClasses={post.cssClasses}
          html={html}
        />
      </div>

      {/* 우측: Graph + TOC */}
      <RightPanel>
        <TableOfContents headings={post.headings} />
      </RightPanel>
    </>
  )
}

// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
	import BlogArticle from '$lib/components/blog/BlogArticle.svelte';
	import RightPanel from '$lib/components/blog/RightPanel.svelte';
	import TableOfContents from '$lib/components/blog/TableOfContents.svelte';
	import type { PageData } from './$types';
	import type { LayoutData } from '../$types';

	let { data }: { data: PageData & LayoutData } = $props();
</script>

<svelte:head>
	<title>{data.post.title} | 1ncarnati0n</title>
	<meta name="description" content={data.post.description} />
</svelte:head>

<!-- 본문 -->
<div class="flex justify-center">
	<BlogArticle
		title={data.post.title}
		date={new Date(data.post.date)}
		readingTime={data.post.readingTime}
		tags={data.post.tags}
		cssClasses={data.post.cssClasses}
		html={data.html}
	/>
</div>

<!-- 우측: Graph + TOC -->
<RightPanel graphData={data.graphData}>
	{#snippet extra()}
		<TableOfContents headings={data.post.headings} />
	{/snippet}
</RightPanel>
