// src/lib/components/ui/Button.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		children: Snippet;
		size?: 'sm' | 'md' | 'lg';
		href?: string;
		external?: boolean;
		onclick?: () => void;
		disabled?: boolean;
		class?: string;
	}

	let {
		children,
		size = 'md',
		href,
		external = false,
		onclick,
		disabled = false,
		class: className = '',
	}: Props = $props();

	let classes = $derived(`btn btn-${size} ${className}`);
</script>

{#if href}
	{#if external}
		<a {href} target="_blank" rel="noopener noreferrer" class={classes}>
			{@render children()}
		</a>
	{:else}
		<a {href} class={classes}>
			{@render children()}
		</a>
	{/if}
{:else}
	<button {onclick} {disabled} class={classes}>
		{@render children()}
	</button>
{/if}

// src/components/ui/Button.tsx
import Link from 'next/link'

interface ButtonProps {
  children: React.ReactNode
  size?: 'sm' | 'md' | 'lg'
  href?: string
  external?: boolean
  onClick?: () => void
  disabled?: boolean
  className?: string
}

export function Button({
  children,
  size = 'md',
  href,
  external = false,
  onClick,
  disabled = false,
  className = '',
}: ButtonProps) {
  const classes = `btn btn-${size} ${className}`

  if (href) {
    if (external) {
      return (
        <a href={href} target="_blank" rel="noopener noreferrer" className={classes}>
          {children}
        </a>
      )
    }
    return <Link href={href} className={classes}>{children}</Link>
  }

  return (
    <button onClick={onClick} disabled={disabled} className={classes}>
      {children}
    </button>
  )
}
